name: Avatars

on:
  workflow_dispatch:

jobs:
  avatars:
    name: Avatars
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: zulu

      - name: Cache Jbang
        uses: actions/cache@v2
        with:
          path: ~/.jbang/cache/
          key: ${{ runner.os }}-jbang-cache-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-

      - name: Update Avatars
        run: |
          cd resources
          ./jbang avatars.java ${{ secrets.TWITTER_TOKEN }} ../images/avatars

      - name: Commit Changes
        run: |
          git add images/avatars
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit -a -m "Update avatars"
          git push origin master